### ISSUE TITLE
Support for Bandit?

### ISSUE THREAD

**Issue by warmwaffles** [andrewtimberlake/sham#1]
I see that plug cowboy is used, do you have plans to support [Bandit](https://github.com/mtrudel/bandit) as an optional underlying http(s) server? I'm looking to replace Bypass and this seems super promising.

**Comment by andrewtimberlake** [comment]
Not yet. Is there a reason using Bandit would be advantageous?

**Comment by warmwaffles** [comment]
Other than the fact I don't have to pull down cowboy and use `ranch`. Currently fighting with upgrading ranch and other dependencies relying on it being at a specific version. This would be one less thing. But no worries.

**Comment by andrewtimberlake** [comment]
I’ll have a look at what it might take to support both

**Comment by warmwaffles** [comment]
It's not super critical, just a passing thought. I'll close this.

**Comment by andrewtimberlake** [comment]
Hi @warmwaffles I’ve added support for Bandit
I’ve tested that the optional server works on projects I have that use Plug.Cowboy
Please test that it works on your non cowboy project.

**Comment by warmwaffles** [comment]
Awesome, I'll take a look

**Comment by warmwaffles** [comment]
Yea @andrewtimberlake this works like a charm. Thanks a ton!
